### ISSUE TITLE
ვერ გავაკეთე!

### ISSUE THREAD

**Issue by zura03geolab** [developer--/PROJECT_MAKE_A_PRESENT#2]
ჯემო ინტენტით მინდოდა დეტალური გვერდი გამეკეთებინა.

ვიდეო გაკვეთილებს ვუყურე, მაგის მსგავსად გავაკეთე ყველაფერი. საჭირო ექთივითები და კლასებიც გაკეთებული მაქვს. დღეს სხვა ხერხითაც ვცადე, მაგრამ არ გამომივიდა.

Tost-ი დავტოვე, რომ პროგრამა გაეშვას.

იქნებ გადახედო და დამეხმარო.

**Comment by developer--** [comment]
onClick ში სადაც ინფრმაცია გადმოგეცემა, შექმენი ინტენტი და გადააწოდე ინფორმაციაც
Intent intent = new Intent(MainActivity.this, detaluri_gvedi.class);
.....
startActivity(intent);

**Comment by developer--** [comment]
Bundle extras = getIntent().getExtras();
String data = extras.getString("test"):

ესე ცადე აბა ინფორმაციის ამოღება

**Comment by developer--** [comment]
თუ არ იზამს ერორი რაც გაქვს დაწერე აქ

**Comment by developer--** [comment]
დააკოპირე მთლიანად

**Comment by zura03geolab** [comment]
კიდევ არ გამომივიდა. ასეთი რა არის, რომ ვერ გავაკეთე.

**Comment by developer--** [comment]
მთლიანი ერორი ჩამიკოპირე

**Comment by zura03geolab** [comment]
--------- beginning of crash
07-28 17:12:31.854 2966-2966/project.afinal.vashakidze.zura.finalproject E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                           Process: project.afinal.vashakidze.zura.finalproject, PID: 2966
                                                                                           android.content.ActivityNotFoundException: Unable to find explicit activity class {project.afinal.vashakidze.zura.finalproject/project.afinal.vashakidze.zura.finalproject.item_details}; have you declared this activity in your AndroidManifest.xml?
                                                                                               at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
                                                                                               at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
                                                                                               at android.app.Activity.startActivityForResult(Activity.java:3917)
                                                                                               at android.app.Activity.startActivityForResult(Activity.java:3877)
                                                                                               at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
                                                                                               at android.app.Activity.startActivity(Activity.java:4200)
                                                                                               at android.app.Activity.startActivity(Activity.java:4168)
                                                                                               at project.afinal.vashakidze.zura.finalproject.MainActivity$1.onItemClick(MainActivity.java:63)
                                                                                               at project.afinal.vashakidze.zura.finalproject.adapter.RecylerListAdapter$MyViewHolder$1.onClick(RecylerListAdapter.java:61)
                                                                                               at android.view.View.performClick(View.java:5198)
                                                                                               at android.view.View$PerformClick.run(View.java:21147)
                                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-28 17:12:34.524 2966-2966/project.afinal.vashakidze.zura.finalproject I/Process: Sending signal. PID: 2966 SIG: 9

**Comment by zura03geolab** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="project.afinal.vashakidze.zura.finalproject">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by developer--** [comment]
<?xml version="1.0" encoding="utf-8"?>
package="project.afinal.vashakidze.zura.finalproject">

<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:supportsRtl="true"
    android:theme="@style/AppTheme">
    <activity android:name=".MainActivity">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
  <activity android:name=". item_details" />
</application>
